/**
 * TenderAlert — Real Supabase Adapter (REST/PostgREST-based, dependency-free)
 *
 * Implements the exact same { insert(record) } interface as
 * mock-supabase-adapter.js, so insertion-executor.js needs ZERO changes to
 * use this instead of the mock — that seam was designed for exactly this
 * swap.
 *
 * Uses Node's built-in global fetch() against Supabase's PostgREST REST API
 * directly — the same dependency-free pattern the live dashboard already
 * uses for reads (dashboard-supabase.html), just for a write here, and
 * server-side only. No @supabase/supabase-js or any other package is
 * installed or required; none is needed.
 *
 * CREDENTIALS: this file never contains a real URL or key. Both are read
 * ONLY from environment variables, at call time, inside insert() — never
 * at module-load time, never cached in a module-level variable, and never
 * included in any thrown error message.
 *
 *   SUPABASE_URL                — bare project URL, e.g. https://xxxxx.supabase.co
 *                                  (same convention already used by
 *                                  dashboard-supabase.html — no trailing
 *                                  /rest/v1/, this code appends that itself)
 *   SUPABASE_SERVICE_ROLE_KEY   — a write-capable key. No INSERT policy has
 *                                  ever been confirmed on Tenders for any
 *                                  role, so this almost certainly needs to
 *                                  be the service_role key (bypasses RLS),
 *                                  not the anon key the dashboard uses for
 *                                  reads. That assumption should be
 *                                  confirmed before a first real insert —
 *                                  this adapter itself is agnostic to which
 *                                  key tier is supplied, it just sends
 *                                  whatever string is in this variable.
 *
 * This module does NOT normalize, validate, deduplicate, enrich, or
 * re-map fields. record-assembly.js already produced the exact shape this
 * table expects (Requirements/Documents as JSON-serialized text, deadline
 * as plain YYYY-MM-DD, id/created_at omitted) — this adapter sends that
 * object as-is and does not alter it.
 */

'use strict';

function readRequiredEnv(varName) {
  const value = process.env[varName];
  if (!value || String(value).trim() === '') {
    throw new Error('Missing required environment variable: ' + varName);
  }
  return value;
}

/**
 * createSupabaseAdapter(options?) -> { insert(record) -> Promise<insertedRow> }
 * options.tableName defaults to 'Tenders' — a table name, never a secret,
 * safe to have a default.
 */
function createSupabaseAdapter(options) {
  options = options || {};
  const tableName = options.tableName || 'Tenders';

  return {
    async insert(record) {
      // Last-line-of-defense guard: id/created_at must never be sent — the
      // database generates both (GENERATED BY DEFAULT AS IDENTITY, and
      // default now() respectively). Fail loudly rather than silently
      // stripping, in case some future upstream bug ever adds these.
      if (Object.prototype.hasOwnProperty.call(record, 'id') ||
          Object.prototype.hasOwnProperty.call(record, 'created_at')) {
        throw new Error('Supabase insert refused: record must not include id or created_at — both are database-generated.');
      }

      const supabaseUrl = readRequiredEnv('SUPABASE_URL');
      const supabaseKey = readRequiredEnv('SUPABASE_SERVICE_ROLE_KEY');

      const endpoint = supabaseUrl.replace(/\/+$/, '') + '/rest/v1/' + encodeURIComponent(tableName);

      let response;
      try {
        response = await fetch(endpoint, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            apikey: supabaseKey,
            Authorization: 'Bearer ' + supabaseKey,
            // return=representation is the PostgREST equivalent of
            // .insert(record).select() — it hands back the full inserted
            // row (including the DB-generated id/created_at) in one call.
            Prefer: 'return=representation'
          },
          body: JSON.stringify(record)
        });
      } catch (networkErr) {
        // Deliberately generic: never forward the raw error object, which
        // could in principle echo connection details tied to the request.
        throw new Error('Supabase insert failed: network error while contacting the database.');
      }

      let body;
      try {
        body = await response.json();
      } catch (parseErr) {
        throw new Error('Supabase insert failed: could not parse the database response (HTTP ' + response.status + ').');
      }

      if (!response.ok) {
        // Surface only PostgREST's own 'message'/'code' fields — never the
        // full raw error body, to avoid any chance of request/connection
        // details leaking through an unusual PostgREST error path.
        const message = (body && body.message) ? body.message : ('HTTP ' + response.status);
        const code = (body && body.code) ? (' [' + body.code + ']') : '';
        throw new Error('Supabase insert failed: ' + message + code);
      }

      // PostgREST returns an array of inserted rows for return=representation.
      const insertedRow = Array.isArray(body) ? body[0] : body;
      if (!insertedRow) {
        throw new Error('Supabase insert failed: no row was returned by the database.');
      }

      return insertedRow;
    }
  };
}

module.exports = { createSupabaseAdapter };
